# **Atak primal na problemie LWE**
## **Demonstracyjne przykłady działania ataku**

In [1]:
from primal_attack_lwe import run_primal_attack
import numpy as np

SEEDS = [i for i in range(5)]

### **Przykład dla małych parametrów - redukcja BKZ**

In [2]:
# dla malych demonstracyjnych parametrow - niewielki wymiar problemu
result_easy = run_primal_attack(
    reduction_method="BKZ",
    n=4,
    m=8,
    q=97,
    S=[-1, 0, 1],
    E=[-1, 0, 1],
)

Parametry LWE:
n= 4
m= 8
q= 97
Sekret i błąd wygenerowane w kryptosystemie:
s= [-1  1 -1 -1]
e= [-1  0 -1  1  0  1  0  1]
Dane publiczne
A=
[[62 30 65 11]
 [52 87 32 80]
 [78 87 29 56]
 [70 42 10 44]
 [55  6 69 64]
 [68 84 21 18]
 [68 67 80 73]
 [59 89 17  8]]
b= [85 20 20 16 12 75 40  6]
Baza kraty embeddingowej
[[ 97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.]
 [-62. -52. -78. -70. -55. -68. -68. -59.   1.   0.   0.   0.   0.]
 [-30. -87. -87. -42.  -6. -84. -67. -89.   0.   1.   0.   0.   0.]
 [-65

### **Przykład dla małych parametrów - redukcja LLL**

In [4]:
# dla malych demonstracyjnych parametrow - niewielki wymiar problemu
result_easy = run_primal_attack(
    reduction_method="LLL",
    n=4,
    m=8,
    q=97,
    S=[-1, 0, 1],
    E=[-1, 0, 1],
)

Parametry LWE:
n= 4
m= 8
q= 97
Sekret i błąd wygenerowane w kryptosystemie:
s= [-1 -1  0  0]
e= [-1 -1 -1  1  0  0 -1 -1]
Dane publiczne
A=
[[ 5 83 43 47]
 [ 6 40 66 74]
 [90  9 82 25]
 [64 76 95 42]
 [34 94 28 45]
 [68 23 71 60]
 [60 44 17 45]
 [89  5 11 49]]
b= [ 8 50 94 55 66  6 89  2]
Baza kraty embeddingowej
[[ 97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.]
 [ -5.  -6. -90. -64. -34. -68. -60. -89.   1.   0.   0.   0.   0.]
 [-83. -40.  -9. -76. -94. -23. -44.  -5.   0.   1.   0.   0.   0.]
 [-43

### **Eksperymenty dla małych parametrów dla róznych seedów**

#### **BKZ**

In [7]:
easy_results_bkz = []

print("Eksperyment dla małych parametrów dla BKZ")
for seed in SEEDS:
    print("================================================")
    print(f"Demonstrakcja łatwego ataku dla seeda {seed}")
    np.random.seed(seed=seed)

    easy_res = run_primal_attack(
        reduction_method="BKZ",
        n=4,
        m=8,
        q=97,
        S=[-1, 0, 1],
        E=[-1, 0, 1],
    )

    easy_results_bkz.append(easy_res)
    print("================================================")

Eksperyment dla małych parametrów dla BKZ
Demonstrakcja łatwego ataku dla seeda 0
Parametry LWE:
n= 4
m= 8
q= 97
Sekret i błąd wygenerowane w kryptosystemie:
s= [ 1 -1  0  0]
e= [ 1 -1  0  0  0 -1  1 -1]
Dane publiczne
A=
[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]
 [39 87 46 88]
 [81 37 25 77]
 [72  9 20 80]
 [69 79 47 64]]
b= [95 57 46 76 49 43 64 86]
Baza kraty embeddingowej
[[ 97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.]
 [-44. -67. -36. -88. -39. -81. -72. -69.   1.   0.   0.   

#### **LLL**

In [8]:
easy_results_lll = []

print("Eksperyment dla małych parametrów dla LLL")
for seed in SEEDS:
    print("================================================")
    print(f"Demonstrakcja łatwego ataku dla seeda {seed}")
    np.random.seed(seed=seed)

    easy_res = run_primal_attack(
        reduction_method="LLL",
        n=4,
        m=8,
        q=97,
        S=[-1, 0, 1],
        E=[-1, 0, 1],
    )

    easy_results_lll.append(easy_res)
    print("================================================")

Eksperyment dla małych parametrów dla LLL
Demonstrakcja łatwego ataku dla seeda 0
Parametry LWE:
n= 4
m= 8
q= 97
Sekret i błąd wygenerowane w kryptosystemie:
s= [ 1 -1  0  0]
e= [ 1 -1  0  0  0 -1  1 -1]
Dane publiczne
A=
[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]
 [39 87 46 88]
 [81 37 25 77]
 [72  9 20 80]
 [69 79 47 64]]
b= [95 57 46 76 49 43 64 86]
Baza kraty embeddingowej
[[ 97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.]
 [-44. -67. -36. -88. -39. -81. -72. -69.   1.   0.   0.   

### **Przykład dla większych parametrów - redukcja BKZ**

In [10]:
# trudniejszy przykład
result_medium = run_primal_attack(
    reduction_method="BKZ",
    n=24,
    m=48,
    q=769,
    S=[-2, -1, 0, 1, 2],
    E=[-3, -2, -1, 0, 1, 2, 3],
)

Parametry LWE:
n= 24
m= 48
q= 769
Sekret i błąd wygenerowane w kryptosystemie:
s= [-2 -2 -1 -2  2  0  2 -1 -1  2  1 -2  1  2 -2 -2  0  1  2  2  0 -1  0  1]
e= [ 2 -2  2  1  0 -3 -2 -1  3  1  3 -3 -1 -2 -3  0  3  0 -1  3  1 -2  0 -2
 -3  0 -2  2  1 -3 -1 -3  2  1  1 -2  1  0  0  1 -3  2  1  0 -3  2 -2 -1]
Dane publiczne
A=
[[ 95 255 562 ... 749 711 466]
 [439 181 499 ... 264 484 543]
 [ 78   9 125 ...  86 639 527]
 ...
 [111 142 160 ... 192 190 558]
 [ 50 115 166 ... 706 319 459]
 [395 105 768 ... 257 199 606]]
b= [ 78 306 127 106 576 191 684 426 646 191 718  99  81 560 631 402  99 216
 705 650 680 292 725 695 283 570 241 560 396 562  97 721 362 591  77 599
 237 437 619 112  96  42 163 368 634 190 481 439]
Baza kraty embeddingowej
[[ 769.    0.    0. ...    0.    0.    0.]
 [   0.  769.    0. ...    0.    0.    0.]
 [   0.    0.  769. ...    0.    0.    0.]
 ...
 [-711. -484. -639. ...    1.    0.    0.]
 [-466. -543. -527. ...    0.    1.    0.]
 [  78.  306.  127. ...    0.    0.    1

### **Przykład dla większych parametrów - redukcja LLL**

In [11]:
# trudniejszy przykład
result_medium = run_primal_attack(
    reduction_method="LLL",
    n=24,
    m=48,
    q=769,
    S=[-2, -1, 0, 1, 2],
    E=[-3, -2, -1, 0, 1, 2, 3],
)

Parametry LWE:
n= 24
m= 48
q= 769
Sekret i błąd wygenerowane w kryptosystemie:
s= [ 2  0  0  0 -1  1  2  2 -2 -2 -1  2  0 -1  0 -1 -1  1 -2  2  0  0 -2  2]
e= [-1  0  0  1  3  1 -3 -2 -3 -2 -2 -1  1  1 -3  1 -2  1  1 -1  1  2  1 -3
  2  3  0  1 -1  1  2  0  1  3  1  0  1  2  1  2 -2  3  3  1 -1  3  2  1]
Dane publiczne
A=
[[636 292 468 ...  19 167 327]
 [620   3 442 ... 684 239 332]
 [720 402 474 ... 100 313 344]
 ...
 [103 528 238 ... 269 494 723]
 [256  77 556 ...  58 293 117]
 [ 89 251 425 ... 349 414 608]]
b= [ 16 501 699 669 749 331 260 610 529 704 434 483  65 465 122 448 530 730
  72 204 593 506 146  59 507  62 181 339 485 641 429 132 390 489 266 605
 101 213 185 156 689 639 651 109 105 724 733 295]
Baza kraty embeddingowej
[[ 769.    0.    0. ...    0.    0.    0.]
 [   0.  769.    0. ...    0.    0.    0.]
 [   0.    0.  769. ...    0.    0.    0.]
 ...
 [-167. -239. -313. ...    1.    0.    0.]
 [-327. -332. -344. ...    0.    1.    0.]
 [  16.  501.  699. ...    0.    0.    1

### **Eksperymenty dla większych parametrów dla róznych seedów**

#### **BKZ**

In [14]:
medium_results_bkz = []

print("Eksperyment dla większych parametrów dla BKZ")
for seed in SEEDS:
    print("================================================")
    print(f"Demonstrakcja dla ataku średniej trudniści dla seeda {seed}")
    np.random.seed(seed=seed)

    res_medium = run_primal_attack(
        reduction_method="BKZ",
        n=24,
        m=48,
        q=769,
        S=[-2, -1, 0, 1, 2],
        E=[-3, -2, -1, 0, 1, 2, 3],
    )

    medium_results_bkz.append(res_medium)
    print("================================================")

Eksperyment dla większych parametrów dla BKZ
Demonstrakcja dla ataku średniej trudniści dla seeda 0
Parametry LWE:
n= 24
m= 48
q= 769
Sekret i błąd wygenerowane w kryptosystemie:
s= [ 0 -1  2 -2  2  0  0 -2  0 -2  0  2  1 -1 -1  1  1 -2  0  2 -1  1  1  1]
e= [-1  2  1  0  1 -2 -3 -3 -2 -3  0  2  3 -1 -3 -2 -1 -2  0 -2  2  0 -3 -1
  1  2 -1  1  3 -3 -2  3  2  2  0  0  3  0  3 -3 -3  2  1 -1 -1  3 -2  1]
Dane publiczne
A=
[[684 559 629 ... 174 600 677]
 [537  72 115 ... 151 675 510]
 [459 183  28 ... 430  82  91]
 ...
 [418 656 257 ...  83 505 396]
 [685  10 500 ... 216 269  78]
 [583 695 300 ...  41 474 752]]
b= [154 523 485 560 340 322 488 439 559 484 353 658 424 507 505 365 141 707
 595 470 433 541   1 401 702 180 230 762 462 149 187 464 495 303 107  78
 627 247 207 725 667 313 733 422 462 607 509 498]
Baza kraty embeddingowej
[[ 769.    0.    0. ...    0.    0.    0.]
 [   0.  769.    0. ...    0.    0.    0.]
 [   0.    0.  769. ...    0.    0.    0.]
 ...
 [-600. -675.  -82. ...   

#### **LLL**

In [15]:
medium_results_lll = []

print("Eksperyment dla większych parametrów dla LLL")
for seed in SEEDS:
    print("================================================")
    print(f"Demonstrakcja dla ataku średniej trudniści dla seeda {seed}")
    np.random.seed(seed=seed)

    res_medium = run_primal_attack(
        reduction_method="LLL",
        n=24,
        m=48,
        q=769,
        S=[-2, -1, 0, 1, 2],
        E=[-3, -2, -1, 0, 1, 2, 3],
    )

    medium_results_lll.append(res_medium)
    print("================================================")

Eksperyment dla większych parametrów dla LLL
Demonstrakcja dla ataku średniej trudniści dla seeda 0
Parametry LWE:
n= 24
m= 48
q= 769
Sekret i błąd wygenerowane w kryptosystemie:
s= [ 0 -1  2 -2  2  0  0 -2  0 -2  0  2  1 -1 -1  1  1 -2  0  2 -1  1  1  1]
e= [-1  2  1  0  1 -2 -3 -3 -2 -3  0  2  3 -1 -3 -2 -1 -2  0 -2  2  0 -3 -1
  1  2 -1  1  3 -3 -2  3  2  2  0  0  3  0  3 -3 -3  2  1 -1 -1  3 -2  1]
Dane publiczne
A=
[[684 559 629 ... 174 600 677]
 [537  72 115 ... 151 675 510]
 [459 183  28 ... 430  82  91]
 ...
 [418 656 257 ...  83 505 396]
 [685  10 500 ... 216 269  78]
 [583 695 300 ...  41 474 752]]
b= [154 523 485 560 340 322 488 439 559 484 353 658 424 507 505 365 141 707
 595 470 433 541   1 401 702 180 230 762 462 149 187 464 495 303 107  78
 627 247 207 725 667 313 733 422 462 607 509 498]
Baza kraty embeddingowej
[[ 769.    0.    0. ...    0.    0.    0.]
 [   0.  769.    0. ...    0.    0.    0.]
 [   0.    0.  769. ...    0.    0.    0.]
 ...
 [-600. -675.  -82. ...   

### **Przykład dla trudnych parametrów - redukcja BKZ**

In [16]:
result_hard = run_primal_attack(
    reduction_method="BKZ",
    n=50,
    m=100,
    q=257,
    S=list(range(-20, 21)),
    E=list(range(-20, 21)),
)

Parametry LWE:
n= 50
m= 100
q= 257
Sekret i błąd wygenerowane w kryptosystemie:
s= [ 10   3   3   1  17  16   3  10 -20 -10  14   4  13  -6 -13  10 -12   5
  15  18  19  14   3  20  -6   2 -12  -6 -15   4 -15 -17  -8  -5  -9  13
  -4  -7 -20   8  -1  -3   3   0  12  20   7 -12 -13  12]
e= [-14 -15  17  13   4   8 -14  20  20  -2  -7  15  15   4 -18  14   3 -11
 -18  -2   5   5   0  -8   1  -5  12  18 -16  12  -3   2  -2  14  -7 -12
  18   4  -6  18  -5   2   7  -3 -18   7  11 -12  17   2  18 -17 -20 -12
   2   1  -9  11  -7  13  -8   7   7   9 -16  18 -10   5  -5  -8  -6  17
   3   5  14  -4  -5 -15  -2  16 -14  16  15  -4   2  20 -10 -20   5  19
 -18  -2 -10  -4  17   8   2   1 -13  20]
Dane publiczne
A=
[[237  42 185 ... 135  19 167]
 [108   3  94 ...   9  28 138]
 [127  85 160 ... 181 226 191]
 ...
 [ 60  68  17 ... 252 239 230]
 [228  91 211 ... 131 197  80]
 [211 227  42 ...   0 201 155]]
b= [149 216 108 245 147  60  48 117 115  74  48  28 171  82  57 171 187  18
  48 149 248 244 

### **Przykład dla trudnych parametrów - redukcja LLL**

In [17]:
result_hard = run_primal_attack(
    reduction_method="LLL",
    n=50,
    m=100,
    q=257,
    S=list(range(-20, 21)),
    E=list(range(-20, 21)),
)

Parametry LWE:
n= 50
m= 100
q= 257
Sekret i błąd wygenerowane w kryptosystemie:
s= [ 18  15  10  -9  -3 -20   4 -11  16  14  -1  17  -6  19   1   1  12 -15
   7   3   2  10   4  -8  14  -1  11  -4  10  20  16   2  -1  10  14  10
  15  15 -13   8   6   8   4  15  11   2 -12   2   4  11]
e= [-18  18  11 -16  11  -5  14 -13   1  19 -10  16 -17   0   6   9  12 -17
  13   4  -7 -13  -2 -15 -10  18   3  -8 -14   3  14  -9   1   4  -8  -7
  -5  18  12  -1 -19  10  -7 -13 -13  -9   2   2  -2 -14 -19 -20  -6  -9
 -13  -7  18  -6   8 -13   4  -3   1 -14  -7  19   3 -19  12  11   1 -16
  11   3 -13   3 -15   8 -14   1  -6 -10  12  -7 -13  11  20  -7  -6  12
  -9   6  -3 -11  14  11 -17  -1  10   7]
Dane publiczne
A=
[[211  55 222 ... 252 211  45]
 [140 219  99 ...  57 185 130]
 [ 57 190 162 ...  95 169  68]
 ...
 [ 17 187  84 ...  35 123 244]
 [150 225  30 ...  77  77  64]
 [ 55 225 130 ... 147 113 235]]
b= [ 29 108  90   5 209 187 189  38 125 175 150  57  44 163  22 191  96 147
 107 153   0 219 

### **Eksperymenty dla trudnych parametrów dla róznych seedów**

#### **BKZ**

In [19]:
hard_results_bkz = []

print("Eksperyment dla trudnych parametrów dla BKZ")
for seed in SEEDS:
    print("================================================")
    print(f"Demonstrakcja dla trudnego ataku dla seeda {seed}")
    np.random.seed(seed=seed)

    res_hard = run_primal_attack(
        reduction_method="BKZ",
        n=50,
        m=100,
        q=257,
        S=list(range(-20, 21)),
        E=list(range(-20, 21)),
    )

    hard_results_bkz.append(res_hard)
    print("================================================")

Eksperyment dla trudnych parametrów dla BKZ
Demonstrakcja dla trudnego ataku dla seeda 0
Parametry LWE:
n= 50
m= 100
q= 257
Sekret i błąd wygenerowane w kryptosystemie:
s= [ 10 -15  -9  -7  -8 -13 -15 -10  10 -17  14 -19  -4  19  -3 -13  -2   1
   2  10 -16  11 -17 -11 -11  14  18  10  -8 -12   4  16 -11 -14 -12  -3
 -11 -19  16 -20  -6   7   6  14 -15 -13  -2  -5   9  18]
e= [ -4 -17 -15  17   6  14  13   4  14 -10 -18 -19 -20  -9 -13  15  -3  20
 -12  17  12 -19 -16  -3   8  11  -3  16 -20  -1   5   9 -13   6 -14  11
 -17 -16 -19  -8 -12  13  13   9   9   2   5   9 -17   7  20  -7   6   4
  14   5  17  11  -5   2  13  -9  18  18  -3   8   0  16 -12 -15  10 -18
   0   4  -7  -1  13  18   8  -4  -1  16  -5  17  18 -10  -1 -11  -7 -11
   9 -19  -1  12  14  10  16   6  20 -20]
Dane publiczne
A=
[[172  47 117 ... 119  82  91]
 [ 99  53 121 ...  32 182 128]
 [174  42 184 ... 215  43  32]
 ...
 [141 130  84 ... 169  90  84]
 [224  12  93 ...  18 187  15]
 [216  23 161 ...  67   4 180]]
b= [

#### **LLL**

In [20]:
hard_results_lll = []

print("Eksperyment dla trudnych parametrów dla LLL")
for seed in SEEDS:
    print("================================================")
    print(f"Demonstrakcja dla trudnego ataku dla seeda {seed}")
    np.random.seed(seed=seed)

    res_hard = run_primal_attack(
        reduction_method="LLL",
        n=50,
        m=100,
        q=257,
        S=list(range(-20, 21)),
        E=list(range(-20, 21)),
    )

    hard_results_lll.append(res_hard)
    print("================================================")

Eksperyment dla trudnych parametrów dla LLL
Demonstrakcja dla trudnego ataku dla seeda 0
Parametry LWE:
n= 50
m= 100
q= 257
Sekret i błąd wygenerowane w kryptosystemie:
s= [ 10 -15  -9  -7  -8 -13 -15 -10  10 -17  14 -19  -4  19  -3 -13  -2   1
   2  10 -16  11 -17 -11 -11  14  18  10  -8 -12   4  16 -11 -14 -12  -3
 -11 -19  16 -20  -6   7   6  14 -15 -13  -2  -5   9  18]
e= [ -4 -17 -15  17   6  14  13   4  14 -10 -18 -19 -20  -9 -13  15  -3  20
 -12  17  12 -19 -16  -3   8  11  -3  16 -20  -1   5   9 -13   6 -14  11
 -17 -16 -19  -8 -12  13  13   9   9   2   5   9 -17   7  20  -7   6   4
  14   5  17  11  -5   2  13  -9  18  18  -3   8   0  16 -12 -15  10 -18
   0   4  -7  -1  13  18   8  -4  -1  16  -5  17  18 -10  -1 -11  -7 -11
   9 -19  -1  12  14  10  16   6  20 -20]
Dane publiczne
A=
[[172  47 117 ... 119  82  91]
 [ 99  53 121 ...  32 182 128]
 [174  42 184 ... 215  43  32]
 ...
 [141 130  84 ... 169  90  84]
 [224  12  93 ...  18 187  15]
 [216  23 161 ...  67   4 180]]
b= [