In [1]:
from primal_attack_lwe import run_primal_attack
import numpy as np

In [2]:
# dla malych demonstracyjnych parametrow - niewielki wymiar problemu
result_easy = run_primal_attack(
    reduction_mathod="BKZ",
    n=4,
    m=8,
    q=97,
    S=[-1, 0, 1],
    E=[-1, 0, 1],
)

Parametry LWE:
n= 4
m= 8
q= 97
Sekret i błąd wygenerowane w kryptosystemie:
s= [-1  0  1 -1]
e= [ 0 -1  1  1 -1 -1  0 -1]
Dane publiczne
A=
[[59 14 55 74]
 [70 24 86 88]
 [11 35  2 41]
 [39 73 86 88]
 [60 83 69 80]
 [17  5 68 52]
 [16 17 10 11]
 [93 26 11  0]]
b= [19 24 48 57 25 95 80 14]
Baza kraty embeddingowej
[[ 97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.]
 [-59. -70. -11. -39. -60. -17. -16. -93.   1.   0.   0.   0.   0.]
 [-14. -24. -35. -73. -83.  -5. -17. -26.   0.   1.   0.   0.   0.]
 [-55

In [ ]:
# dla malych demonstracyjnych parametrow - niewielki wymiar problemu
result_easy = run_primal_attack(
    reduction_mathod="LLL",
    n=4,
    m=8,
    q=97,
    S=[-1, 0, 1],
    E=[-1, 0, 1],
)

Parametry LWE:
n= 4
m= 8
q= 97
Sekret i błąd wygenerowane w kryptosystemie:
s= [0 1 1 0]
e= [ 0  1  0  0 -1  1 -1 -1]
Dane publiczne
A=
[[62 90 82 38]
 [31 73 42 45]
 [39 28 75 28]
 [93  6 15 27]
 [88 16  0 26]
 [33  4 10 76]
 [ 2 68 52 56]
 [20 78 29 75]]
b= [75 19  6 21 15 15 22  9]
Baza kraty embeddingowej
[[ 97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.]
 [-62. -31. -39. -93. -88. -33.  -2. -20.   1.   0.   0.   0.   0.]
 [-90. -73. -28.  -6. -16.  -4. -68. -78.   0.   1.   0.   0.   0.]
 [-82. -4

In [3]:
SEEDS = [i for i in range(10)]

In [4]:
easy_results = []

for seed in SEEDS:
    print("================================================")
    print(f"Easy attack demonstration for seed {seed}")
    np.random.seed(seed=seed)

    easy_res = run_primal_attack(
        n=4,
        m=8,
        q=97,
        S=[-1, 0, 1],
        E=[-1, 0, 1],
    )

    easy_results.append(easy_res)
    print("================================================")

Easy attack demonstration for seed 0
Parametry LWE:
n= 4
m= 8
q= 97
Sekret i błąd wygenerowane w kryptosystemie:
s= [ 1 -1  0  0]
e= [ 1 -1  0  0  0 -1  1 -1]
Dane publiczne
A=
[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]
 [39 87 46 88]
 [81 37 25 77]
 [72  9 20 80]
 [69 79 47 64]]
b= [95 57 46 76 49 43 64 86]
Baza kraty embeddingowej
[[ 97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  97.   0.   0.   0.   0.   0.]
 [-44. -67. -36. -88. -39. -81. -72. -69.   1.   0.   0.   0.   0.]
 [-47.  -9. -87. -12. -87. -37.  -9.

In [ ]:
# jeszcze trudniejszy przykład
result_medium = run_primal_attack(
    reduction_mathod="LLL",
    n=24,
    m=48,
    q=769,
    S=[-2, -1, 0, 1, 2],
    E=[-3, -2, -1, 0, 1, 2, 3],
)

Parametry LWE:
n= 24
m= 48
q= 769
Sekret i błąd wygenerowane w kryptosystemie:
s= [ 1 -2  2  2 -1  2 -1  0 -1  1  2  1 -2  1  1  2 -2  1 -1  2 -2 -1 -1 -1]
e= [-1  0  1  0  1  0  2  0 -3  2  2  3 -2  3  3  3 -2 -1 -3 -2 -3  2 -3  3
  2 -1  1 -3 -1 -2 -2  0  0 -3 -1  3  1  0  0  0 -2 -2  3  0  0  2 -2 -3]
Dane publiczne
A=
[[434 296 245 ... 108 371 205]
 [455 247 626 ... 224 290 144]
 [682 624 526 ... 463 395  22]
 ...
 [496 564 400 ... 269 662 443]
 [184  20 149 ... 556 534 753]
 [495 536 299 ...  23 472 188]]
b= [620 655  59 391 118 374 431 514  11 730 559 450 710 431 719  27  40 346
  62  92 303 576 421   1 453 488 627 717  10 719 240 160  66  98 508 751
  23 123 255 172 716 569 274 537  99 424 179 727]
Baza kraty embeddingowej
[[ 769.    0.    0. ...    0.    0.    0.]
 [   0.  769.    0. ...    0.    0.    0.]
 [   0.    0.  769. ...    0.    0.    0.]
 ...
 [-371. -290. -395. ...    1.    0.    0.]
 [-205. -144.  -22. ...    0.    1.    0.]
 [ 620.  655.   59. ...    0.    0.    1

In [ ]:
medium_results = []

for seed in SEEDS:
    print("================================================")
    print(f"Medium attack demonstration for seed {seed}")
    np.random.seed(seed=seed)

    res_medium = run_primal_attack(
        reduction_mathod="LLL",
        n=24,
        m=48,
        q=769,
        S=[-2, -1, 0, 1, 2],
        E=[-3, -2, -1, 0, 1, 2, 3],
    )

    medium_results.append(res_medium)
    print("================================================")

Medium attack demonstration for seed 0
Parametry LWE:
n= 24
m= 48
q= 769
Sekret i błąd wygenerowane w kryptosystemie:
s= [ 0 -1  2 -2  2  0  0 -2  0 -2  0  2  1 -1 -1  1  1 -2  0  2 -1  1  1  1]
e= [-1  2  1  0  1 -2 -3 -3 -2 -3  0  2  3 -1 -3 -2 -1 -2  0 -2  2  0 -3 -1
  1  2 -1  1  3 -3 -2  3  2  2  0  0  3  0  3 -3 -3  2  1 -1 -1  3 -2  1]
Dane publiczne
A=
[[684 559 629 ... 174 600 677]
 [537  72 115 ... 151 675 510]
 [459 183  28 ... 430  82  91]
 ...
 [418 656 257 ...  83 505 396]
 [685  10 500 ... 216 269  78]
 [583 695 300 ...  41 474 752]]
b= [154 523 485 560 340 322 488 439 559 484 353 658 424 507 505 365 141 707
 595 470 433 541   1 401 702 180 230 762 462 149 187 464 495 303 107  78
 627 247 207 725 667 313 733 422 462 607 509 498]
Baza kraty embeddingowej
[[ 769.    0.    0. ...    0.    0.    0.]
 [   0.  769.    0. ...    0.    0.    0.]
 [   0.    0.  769. ...    0.    0.    0.]
 ...
 [-600. -675.  -82. ...    1.    0.    0.]
 [-677. -510.  -91. ...    0.    1.    0.]
 

In [3]:
result_hard = run_primal_attack(
    reduction_mathod="BKZ",
    n=50,
    m=100,
    q=257,
    S=list(range(-20, 21)),
    E=list(range(-20, 21)),
)

Parametry LWE:
n= 50
m= 100
q= 257
Sekret i błąd wygenerowane w kryptosystemie:
s= [-14   3  -8 -13  11 -20  12   0 -12 -14  19  10   2   3  -5   1   8  11
  -3  14 -14  -3  15 -10   4 -20  13 -14   3  10  13 -11  13  -5 -12   8
  -6 -19   6   7  -6  14  -6  16  -5  -2   9  12 -12   7]
e= [ -2 -14  -1   5  -6  20  15   5   7   7 -20  12  -4  16  11  16   2 -12
  -7 -13 -14   8  -1  14  15 -15   3 -18   7  -2  20   5   1  18  -1  -3
  16  -2  -7 -16 -18 -14  16  -9  14   5  14  -5  14 -13  14   3  11 -18
  11   5   2 -19 -13  10 -14 -17   7 -12  16  16   1   7   1 -10  -2  10
   8   7  11 -19 -17 -11   2  -7  10  -8 -10 -20 -13  -1   6 -10 -16  20
   7  20   5 -15  10  13 -14   5   4 -12]
Dane publiczne
A=
[[172 179 117 ...  38 147  81]
 [ 11  14 251 ... 161 132 155]
 [208 121 195 ...  77 187  46]
 ...
 [ 35 209  27 ...  65 143 151]
 [  8  78   3 ... 219 208 138]
 [254   8  30 ...  47 117  27]]
b= [ 43 245 109 138  15 247 166  86 242  76 144  74 157  38  63 239 203 116
 196  18 159  27 

In [ ]:
result_hard = run_primal_attack(
    reduction_mathod="LLL",
    n=50,
    m=100,
    q=257,
    S=list(range(-20, 21)),
    E=list(range(-20, 21)),
)

Parametry LWE:
n= 50
m= 100
q= 257
Sekret i błąd wygenerowane w kryptosystemie:
s= [  3 -12 -13  11 -12  14  17  19  -8  12 -20   2  -1 -19  15   2  12 -17
  17 -14   4  20 -12  -2  -9   0  16  14 -13 -15  -1   4 -18   9 -19 -16
 -13  -7   3 -16  17  17  17  -9   5 -12  10  -6  19   0]
e= [-19  -5 -18   3  -8   3  -2  16 -16  -4 -15  -8   1 -11 -10   2  -9  -6
 -16  10 -16  18  -8 -17   1  17   3   1  12 -14  13  -6  -7   7 -11  14
  -2   3  15   5  -8   5   8   0  18 -19  11   2  14 -11  -3  -5   2 -19
 -17 -16 -20 -20 -12  -7   1  19  17  -8  20  20   2 -17  11   0  10 -11
 -10  12   7 -11  -5 -18  18  -2  18 -14  15  -6  18   1  -5  20 -19  -4
 -10   7  -9   8   4 -13 -18   0 -10  -1]
Dane publiczne
A=
[[225 191  73 ... 201 130 171]
 [ 51 227  83 ...  50  95  84]
 [ 50 161  75 ... 217 211 105]
 ...
 [217  15 232 ... 213  76  83]
 [ 13  12 198 ... 189  67 235]
 [135 193 170 ...  58 118  48]]
b= [ 33 251 180 141 119  12 156  21 128  94 220  94 228 249 174  12  10 248
  22 108 223 146 

In [ ]:
hard_results = []

for seed in SEEDS:
    print("================================================")
    print(f"Hard attack demonstration for seed {seed}")
    np.random.seed(seed=seed)

    res_hard = run_primal_attack(
        reduction_mathod="LLL",
        n=50,
        m=100,
        q=257,
        S=list(range(-20, 21)),
        E=list(range(-20, 21)),
    )

    hard_results.append(res_hard)
    print("================================================")

Hard attack demonstration for seed 0
Parametry LWE:
n= 50
m= 100
q= 257
Sekret i błąd wygenerowane w kryptosystemie:
s= [ 10 -15  -9  -7  -8 -13 -15 -10  10 -17  14 -19  -4  19  -3 -13  -2   1
   2  10 -16  11 -17 -11 -11  14  18  10  -8 -12   4  16 -11 -14 -12  -3
 -11 -19  16 -20  -6   7   6  14 -15 -13  -2  -5   9  18]
e= [ -4 -17 -15  17   6  14  13   4  14 -10 -18 -19 -20  -9 -13  15  -3  20
 -12  17  12 -19 -16  -3   8  11  -3  16 -20  -1   5   9 -13   6 -14  11
 -17 -16 -19  -8 -12  13  13   9   9   2   5   9 -17   7  20  -7   6   4
  14   5  17  11  -5   2  13  -9  18  18  -3   8   0  16 -12 -15  10 -18
   0   4  -7  -1  13  18   8  -4  -1  16  -5  17  18 -10  -1 -11  -7 -11
   9 -19  -1  12  14  10  16   6  20 -20]
Dane publiczne
A=
[[172  47 117 ... 119  82  91]
 [ 99  53 121 ...  32 182 128]
 [174  42 184 ... 215  43  32]
 ...
 [141 130  84 ... 169  90  84]
 [224  12  93 ...  18 187  15]
 [216  23 161 ...  67   4 180]]
b= [119  41 216 221   1  19 251 210  31 214 100 229 153 